src/Entity/Campagne.php
<?php

namespace App\Entity;

use App\Repository\CampagneRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * @ORM\Entity(repositoryClass=CampagneRepository::class)
 */
class Campagne
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom_campagne;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_start;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_end;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="campagnes")
     * @ORM\JoinColumn(nullable=false)
     */
    private $creator;

    /**
     * @ORM\OneToMany(targetEntity=Horaire::class, mappedBy="campagne")
     */
    private $horaires;

    /**
     * @var \DateTime $created_at
     *
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @var \DateTime $updated_at
     *
     * @Gedmo\Timestampable(on="update")
     * @ORM\Column(type="datetime")
     */
    private $updated_at;

    /**
     * @Gedmo\Slug(fields={"nom_campagne"})
     * @ORM\Column(length=128, unique=true)
     */
    private $slug;

    /**
     * @return mixed
     */
    public function getSlug()
    {
        return $this->slug;
    }

    /**
     * @return \DateTime
     */
    public function getCreatedAt(): \DateTime
    {
        return $this->created_at;
    }

    /**
     * @return \DateTime
     */
    public function getUpdatedAt(): \DateTime
    {
        return $this->updated_at;
    }

    public function __construct()
    {
        $this->horaires = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomCampagne(): ?string
    {
        return $this->nom_campagne;
    }

    public function setNomCampagne(string $nom_campagne): self
    {
        $this->nom_campagne = $nom_campagne;

        return $this;
    }

    public function getDateStart(): ?\DateTimeInterface
    {
        return $this->date_start;
    }

    public function setDateStart(\DateTimeInterface $date_start): self
    {
        $this->date_start = $date_start;

        return $this;
    }

    public function getDateEnd(): ?\DateTimeInterface
    {
        return $this->date_end;
    }

    public function setDateEnd(\DateTimeInterface $date_end): self
    {
        $this->date_end = $date_end;

        return $this;
    }

    public function getCreator(): ?User
    {
        return $this->creator;
    }

    public function setCreator(?User $creator): self
    {
        $this->creator = $creator;

        return $this;
    }

    /**
     * @return Collection|Horaire[]
     */
    public function getHoraires(): Collection
    {
        return $this->horaires;
    }

    public function addHoraire(Horaire $horaire): self
    {
        if (!$this->horaires->contains($horaire)) {
            $this->horaires[] = $horaire;
            $horaire->setCampagne($this);
        }

        return $this;
    }

    public function removeHoraire(Horaire $horaire): self
    {
        if ($this->horaires->removeElement($horaire)) {
            // set the owning side to null (unless already changed)
            if ($horaire->getCampagne() === $this) {
                $horaire->setCampagne(null);
            }
        }

        return $this;
    }
}

src/Form/CampagneType.php
<?php

namespace App\Form;

use App\Entity\Campagne;
use App\Entity\User;
use Doctrine\ORM\EntityRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CampagneType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nom_campagne', TextType::class, [
                'attr' => [
                    'placeholder' => 'Choisissez un nom explicit'
                ]
            ])
            ->add('date_start', DateTimeType::class, [
                'label' => 'Date début'
            ])
            ->add('date_end', DateTimeType::class, [
                'label' => 'Date de fin'
            ])
            ->add('creator', EntityType::class, [
                'class' => User::class,
                'label' => 'Créateur',
                'query_builder' => function(EntityRepository $er) {
                    return $er->createQueryBuilder('u')
                        ->orderBy('u.email', 'ASC');
                },
                'choice_label' => 'email'
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Campagne::class,
        ]);
    }
}

src/Controller/CampagneController.php
<?php

namespace App\Controller;

use App\Entity\Campagne;
use App\Form\CampagneType;
use App\Repository\CampagneRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/admin/campagne")
 */
class CampagneController extends AbstractController
{
    /**
     * @Route("/", name="campagne_index", methods={"GET"})
     */
    public function index(CampagneRepository $campagneRepository): Response
    {
        return $this->render('campagne/index.html.twig', [
            'campagnes' => $campagneRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="campagne_new", methods={"GET", "POST"})
     */
    public function new(Request $request): Response
    {
        $campagne = new Campagne();
        $form = $this->createForm(CampagneType::class, $campagne);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($campagne);
            $entityManager->flush();

            return $this->redirectToRoute('campagne_index');
        }

        return $this->render('campagne/new.html.twig', [
            'campagne' => $campagne,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{slug}", name="campagne_show", methods={"GET"})
     */
    public function show(Campagne $campagne): Response
    {
        return $this->render('campagne/show.html.twig', [
            'campagne' => $campagne,
        ]);
    }

    /**
     * @Route("/{slug}/edit", name="campagne_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Campagne $campagne): Response
    {
        $form = $this->createForm(CampagneType::class, $campagne);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('campagne_index');
        }

        return $this->render('campagne/edit.html.twig', [
            'campagne' => $campagne,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="campagne_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Campagne $campagne): Response
    {
        if ($this->isCsrfTokenValid('delete'.$campagne->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($campagne);
            $entityManager->flush();
        }

        return $this->redirectToRoute('campagne_index');
    }
}

templates/campagne/_delete_form.html.twig
<form method="post" action="{{ path('campagne_delete', {'id': campagne.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ campagne.id) }}">
    <br>
    <button class="btn btn-primary btn-danger">Supprimer</button>
</form>

templates/campagne/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-success">{{ button_label|default('Sauvegarder') }}</button>
{{ form_end(form) }}

templates/campagne/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Editer une campagne{% endblock %}

{% block body %}
    <br>
    <h1>Editer une campagne</h1>

    {{ include('campagne/_form.html.twig', {'button_label': 'Mettre à jour'}) }}
    {{ include('campagne/_delete_form.html.twig') }}

    <br>

    <a class="btn btn-sm btn-info" href="{{ path('campagne_index') }}">
        <i class="fas fa-arrow-left"></i>
        Retour à la liste
    </a>
{% endblock %}

templates/campagne/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste Campagnes{% endblock %}

{% block body %}
    <br>
    <h1>Liste des campagnes</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom_campagne</th>
                <th>Date_start</th>
                <th>Date_end</th>
                <th>Créateur</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for campagne in campagnes %}
            <tr>
                <td>{{ campagne.id }}</td>
                <td>{{ campagne.nomCampagne }}</td>
                <td>{{ campagne.dateStart ? campagne.dateStart|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ campagne.dateEnd ? campagne.dateEnd|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('user_show', {'id': campagne.creator.id}) }}">{{ campagne.creator.email|split('@')[0] }}</a>
                </td>
                <td>
                    <a class="btn btn-sm btn-info" href="{{ path('campagne_show', {'slug': campagne.slug}) }}">
                        <i class="fas fa-eye"></i>
                        Voir
                    </a>
                    <a class="btn btn-sm btn-success" href="{{ path('campagne_edit', {'slug': campagne.slug}) }}">
                        <i class="fas fa-edit"></i>
                        Editer
                    </a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">Aucune campagne pour le moment</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a class="btn btn-primary" href="{{ path('campagne_new') }}">
        <i class="fas fa-plus"></i>
        Nouvelle Campagne
    </a>
{% endblock %}

templates/campagne/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouvelle Campagne{% endblock %}

{% block body %}
    <br>
    <h1>Créer une nouvelle campagne</h1>

    {{ include('campagne/_form.html.twig') }}

    <br>
    <a class="btn btn-sm btn-info" href="{{ path('campagne_index') }}">
        <i class="fas fa-arrow-left"></i>
        Retour à la liste
    </a>
{% endblock %}

templates/campagne/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Campagne{% endblock %}

{% block body %}
    <br>
    <h1>Campagne</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ campagne.id }}</td>
            </tr>
            <tr>
                <th>Nom_campagne</th>
                <td>{{ campagne.nomCampagne }}</td>
            </tr>
            <tr>
                <th>Date_start</th>
                <td>{{ campagne.dateStart ? campagne.dateStart|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Date_end</th>
                <td>{{ campagne.dateEnd ? campagne.dateEnd|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Créateur</th>
                <td>
                    <a href="{{ path('user_show', {'id': campagne.creator.id}) }}">{{ campagne.creator.email|split('@')[0] }}</a>
                </td>
            </tr>
        </tbody>
    </table>

    <a class="btn btn-sm btn-info" href="{{ path('campagne_index') }}">
        <i class="fas fa-arrow-left"></i>
        Retour à la liste
    </a>

    <a class="btn btn-sm btn-success" href="{{ path('campagne_edit', {'slug': campagne.slug}) }}">
        <i class="fas fa-edit"></i>
        Editer
    </a>

    {{ include('campagne/_delete_form.html.twig') }}
{% endblock %}